---
version: 1
disable_existing_loggers: True
formatters:
    simple:
        format: '%(asctime)s %(process)-d %(processName)-12s %(thread)-d %(threadName)-21s %(levelname)-8s %(message)s'
#        format: '%(asctime)s %(name)-26s %(levelname)-8s %(processName)-12s %(message)s'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: logs/debug.log
        maxBytes: 1048576 # 1MB
        backupCount: 2
        encoding: utf8
        mode: 'w'

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/info.log
        maxBytes: 1048576 # 1MB
        backupCount: 20
        encoding: utf8
        mode: 'w'

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs/errors.log
        maxBytes: 1048576 # 1MB
        backupCount: 20
        encoding: utf8
        mode: 'w'

loggers:
    my_module:
        level: ERROR
        handlers: [console]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler, debug_file_handler]
...
